apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pyu3g23hq-java-springboot
  janus-idp.io/tekton: pyu3g23hq-java-springboot
  backstage.io/kubernetes-id: pyu3g23hq-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: pyu3g23hq-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
